[dev_tool.script_src]
[[dev_tool.script_src.gists]]
file = "cli.py"
gist_id = "5e40217db8f7a218b28f365a13a14c00"
sha = "996ff9d9d252b1f5d344114635419044da590e85"

[[dev_tool.script_src.repo_contents]]
file = "pyboard.py"
owner = "micropython"
repo = "micropython"
path = "tools/pyboard.py"
ref = "master"
sha = "6376b13c7e333cba79e454e4b306867dc40b0317"

