[tool.black]
line-length = 92
target_version = [ "py34",]
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.vscode
  )/
)
'''

[dev_tool.module]
name = "dev_tool" # Change to your module name
src_dir = "." # Where is the parent folder of the module (relative to project root)
micropython-lib = []

[dev_tool.submodule_dependencies]

[dev_tool.script_src]
[[dev_tool.script_src.gists]]
file = ""
gist_id = ""
sha = ""

[[dev_tool.script_src.repo_contents]]
file = ""
owner = ""
repo = ""
path = ""
ref = ""
sha = ""

